import type { KnowledgeGraphData } from './types';

export const mockKnowledgeGraph: KnowledgeGraphData = {
    graph_metadata: {
        document_id: 'uuid-pdf-123',
        title: 'Introduction to Economics',
        total_concepts: 14,
        last_updated: '2026-04-28T14:30:00Z',
    },
    nodes: [
        // Level 0: Modules
        {
            id: 'mod_micro',
            label: 'Microeconomics',
            type: 'module',
            level: 0,
            description: 'The study of individuals, households and firms\' behavior in decision making and allocation of resources.',
            page_refs: [1, 2],
            importance: 1.0,
            mastery_score: 0.6,
            status: 'in_progress',
        },
        {
            id: 'mod_macro',
            label: 'Macroeconomics',
            type: 'module',
            level: 0,
            description: 'The branch of economics that studies the behavior and performance of an economy as a whole.',
            page_refs: [100, 101],
            importance: 1.0,
            mastery_score: 0.0,
            status: 'locked',
        },

        // Level 1: Chapters (Microeconomics)
        {
            id: 'chap_supply_demand',
            label: 'Supply and Demand',
            type: 'chapter',
            parent: 'mod_micro',
            level: 1,
            description: 'The fundamental model of price determination in a market.',
            page_refs: [12, 13, 15],
            importance: 0.9,
            mastery_score: 0.95,
            status: 'mastered',
        },
        {
            id: 'chap_market_failures',
            label: 'Market Failures',
            type: 'chapter',
            parent: 'mod_micro',
            level: 1,
            description: 'Situations where the allocation of goods and services is not efficient.',
            page_refs: [40, 41],
            importance: 0.8,
            mastery_score: 0.2,
            status: 'in_progress',
        },

        // Level 2: Concepts (Supply and Demand)
        {
            id: 'concept_equilibrium',
            label: 'Market Equilibrium',
            type: 'concept',
            parent: 'chap_supply_demand',
            level: 2,
            description: 'A situation where market supply and demand balance each other.',
            page_refs: [22],
            importance: 0.9,
            mastery_score: 1.0,
            status: 'mastered',
        },
        {
            id: 'concept_elasticity',
            label: 'Price Elasticity',
            type: 'concept',
            parent: 'chap_supply_demand',
            level: 2,
            description: 'Measurement of the change in consumption of a product in relation to a change in its price.',
            page_refs: [18, 19],
            importance: 0.85,
            mastery_score: 0.45,
            status: 'in_progress',
        },
        {
            id: 'concept_surplus',
            label: 'Economic Surplus',
            type: 'concept',
            parent: 'chap_supply_demand',
            level: 2,
            description: 'The sum of consumer surplus and producer surplus.',
            page_refs: [30, 32],
            importance: 0.8,
            mastery_score: 0.0,
            status: 'locked',
        },

        // Level 2: Concepts (Market Failures)
        {
            id: 'concept_externalities',
            label: 'Externalities',
            type: 'concept',
            parent: 'chap_market_failures',
            level: 2,
            description: 'A cost or benefit caused by a producer that is not financially incurred or received by that producer.',
            page_refs: [45],
            importance: 0.85,
            mastery_score: 0.0,
            status: 'locked',
        },
        {
            id: 'concept_public_goods',
            label: 'Public Goods',
            type: 'concept',
            parent: 'chap_market_failures',
            level: 2,
            description: 'A commodity or service that is made available to all members of a society.',
            page_refs: [50],
            importance: 0.75,
            mastery_score: 0.0,
            status: 'locked',
        },

        // Level 1: Chapters (Macroeconomics)
        {
            id: 'chap_gdp',
            label: 'Gross Domestic Product',
            type: 'chapter',
            parent: 'mod_macro',
            level: 1,
            description: 'The monetary measure of the market value of all final goods and services produced in a specific time period.',
            page_refs: [105],
            importance: 0.9,
            mastery_score: 0.0,
            status: 'locked',
        },
        {
            id: 'chap_inflation',
            label: 'Inflation',
            type: 'chapter',
            parent: 'mod_macro',
            level: 1,
            description: 'A general increase in prices and fall in the purchasing value of money.',
            page_refs: [120],
            importance: 0.85,
            mastery_score: 0.0,
            status: 'locked',
        },

        // Level 2: Concepts (Macroeconomics)
        {
            id: 'concept_real_gdp',
            label: 'Real vs Nominal GDP',
            type: 'concept',
            parent: 'chap_gdp',
            level: 2,
            description: 'Understanding inflation adjustments in national output.',
            page_refs: [108],
            importance: 0.8,
            mastery_score: 0.0,
            status: 'locked',
        },
        {
            id: 'concept_cpi',
            label: 'Consumer Price Index',
            type: 'concept',
            parent: 'chap_inflation',
            level: 2,
            description: 'A measure that examines the weighted average of prices of a basket of consumer goods and services.',
            page_refs: [122],
            importance: 0.8,
            mastery_score: 0.0,
            status: 'locked',
        },
        {
            id: 'concept_hyperinflation',
            label: 'Hyperinflation',
            type: 'concept',
            parent: 'chap_inflation',
            level: 2,
            description: 'Very high and typically accelerating inflation.',
            page_refs: [125],
            importance: 0.6,
            mastery_score: 0.0,
            status: 'locked',
        }
    ],
    edges: [
        // Skeleton / Tree (Vertical) - Used for layout
        { id: 'e1', source: 'mod_micro', target: 'chap_supply_demand', relationship: 'parent_child' },
        { id: 'e2', source: 'mod_micro', target: 'chap_market_failures', relationship: 'parent_child' },
        
        { id: 'e3', source: 'chap_supply_demand', target: 'concept_equilibrium', relationship: 'parent_child' },
        { id: 'e4', source: 'chap_supply_demand', target: 'concept_elasticity', relationship: 'parent_child' },
        { id: 'e5', source: 'chap_supply_demand', target: 'concept_surplus', relationship: 'parent_child' },
        
        { id: 'e6', source: 'chap_market_failures', target: 'concept_externalities', relationship: 'parent_child' },
        { id: 'e7', source: 'chap_market_failures', target: 'concept_public_goods', relationship: 'parent_child' },

        { id: 'e8', source: 'mod_macro', target: 'chap_gdp', relationship: 'parent_child' },
        { id: 'e9', source: 'mod_macro', target: 'chap_inflation', relationship: 'parent_child' },

        { id: 'e10', source: 'chap_gdp', target: 'concept_real_gdp', relationship: 'parent_child' },
        { id: 'e11', source: 'chap_inflation', target: 'concept_cpi', relationship: 'parent_child' },
        { id: 'e12', source: 'chap_inflation', target: 'concept_hyperinflation', relationship: 'parent_child' },

        // Neural Net / Cluster (Horizontal) - Hidden from visual tree structure but used by AI
        { id: 'e13', source: 'concept_equilibrium', target: 'concept_externalities', relationship: 'requires', label: 'Failure of equilibrium' },
        { id: 'e14', source: 'concept_real_gdp', target: 'concept_cpi', relationship: 'requires', label: 'Uses CPI for adjustment' },
        { id: 'e15', source: 'concept_elasticity', target: 'concept_cpi', relationship: 'similar_to', label: 'Mathematical similarities in percentage changes' }
    ],
};
